name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: nvidia/cuda:12.3.2-runtime-ubuntu22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y --no-install-recommends \
          curl wget \
          ocl-icd-libopencl1 \
          opencl-headers \
          nano \
          build-essential \
          clinfo pkg-config && \
        rm -rf /var/lib/apt/lists/*
        
        mkdir -p /etc/OpenCL/vendors && \
          echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd
        
        ln -s /usr/local/cuda/lib64/libOpenCL.so.1 /usr/lib/libOpenCL.so
        
        echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
          echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf
        
        export PATH=/usr/local/nvidia/bin:${PATH}
        export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}
        
        export NVIDIA_VISIBLE_DEVICES=all
        export NVIDIA_DRIVER_CAPABILITIES=compute,utility
        
    - name: Build
      run: make all
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
